sudo: true
language: python
      
python:
    - "3.6"
    - "3.5"

before_install:
    - sudo apt-get install python3-pip -y
    - sudo apt-get install python-qt4 -y
    - sudo apt-get install python-lxml -y
    - sudo apt-get install python-six -y
		- sudo apt-get install dirmngr
		- sudo apt-get install libc6-i386 -y
    - bash install_java.sh
		- sudo apt-get update
		- sudo wget https://mafft.cbrc.jp/alignment/software/mafft_7.407-1_amd64.deb
    - sudo dpkg -i mafft_7.407-1_amd64.deb
    - sudo wget https://sco.h-its.org/exelixis/resource/download/software/papara_nt-2.5-static_x86_64.tar.gz

install:
    - pip install -r /home/travis/build/hallamlab/TreeSAPP/requirements.txt
    - pip install pytest-cov

before_script:
    - cd /home/travis/build/hallamlab/TreeSAPP/sub_binaries; cp usearch /usr/bin; cd ../; make; make install

script:
    - py.test -vv tests/treesapp_test.py
    - py.test -vv tests/jplace_utils_test.py
    - py.test -vv tests/fasta_test.py
    - py.test -vv tests/file_parsers_test.py
    - py.test -vv tests/classy_test.py
    
#whitelist
branches:
  only:
    - travis

  except:
    - master
    
notifications:
    email: false