sudo: true
language: python
      
python:
    - "3.6"
    - "3.5"

before_install:
    - sudo apt-get install python3-pip -y
    - sudo apt-get install python-qt4 -y
    - sudo apt-get install python-lxml -y
    - sudo apt-get install python-six -y
    - sudo apt-get update
    - sudo apt-get install oracle-java8-installer -y || true
    - cd /var/lib/dpkg/info && sed -i 's|JAVA_VERSION=8u191|JAVA_VERSION=8u202|' oracle-java8-installer.*
    - sed -i 's|PARTNER_URL=http://download.oracle.com/otn-pub/java/jdk/8u191-b12/2787e4a523244c269598db4e85c51e0c/| PARTNER_URL=https://download.oracle.com/otn-pub/java/jdk/8u202-b08/1961070e4c9b4e26a04e7f5a083f551e/|' oracle-java8-installer.*
    - sed -i 's|SHA256SUM_TGZ=.*|SHA256SUM_TGZ="9a5c32411a6a06e22b69c495b7975034409fa1652d03aeb8eb5b6f59fd4594e0"|' oracle-java8-installer.*
    - sed -i 's|JDIR=jdk1.8.0_191|J_DIR=jdk1.8.0_202|' oracle-java8-installer.*
    - sudo apt-get update
    - sudo apt-get install oracle-java8-installer -y
    - sudo apt-get install oracle-java8-set-default -y
    - wget https://mafft.cbrc.jp/alignment/software/mafft_7.407-1_amd64.deb
    - sudo dpkg -i mafft_7.407-1_amd64.deb
    - wget https://sco.h-its.org/exelixis/resource/download/software/papara_nt-2.5-static_x86_64.tar.gz

install:
    - pip install -r requirements.txt
    - pip install pytest-cov

before_script:
    - cd /home/travis/build/hallamlab/TreeSAPP/sub_binaries; cp usearch /usr/bin; cd ../; make; make install

script:
    - py.test -vv tests/treesapp_test.py
    - py.test -vv tests/jplace_utils_test.py
    - py.test -vv tests/fasta_test.py
    - py.test -vv tests/file_parsers_test.py
    - py.test -vv tests/classy_test.py
    
#whitelist
branches:
  only:
    - travis

  except:
    - master
    
notifications:
    email: false